### ISSUE TITLE
Question: how to find out NAT gateway data transfer usage?

### ISSUE THREAD

**Issue by oponomarov-tu** [1debit/alternat#41]
This is more a question related to evaluating migration to alternat. I'm not an AWS expert, so please go easy on me. :) 

Is there a way how to figure out how much data has been transferred through a NAT gateway in a month without enabling VPC flow logs? If VPC flow logs and [querying](http://kamalzerta.com/how-to-analyze-and-reduce-the-cost-of-aws-nat-gateway/) them with Athena is the only option -- are there any tools that provide some sort of automation, a Terraform module perhaps? I've been struggling to find any of it that's not 4+ years old.

I think putting this information or links to some resources into the readme would really help with the adoption. 

Thanks for a great tool!

**Comment by smithatlanta** [comment]
Take a look here:  https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway-cloudwatch.html

**Comment by bwhaley** [comment]
It's unfortunately harder than it should be. Querying VPC flow logs from Athena is the right way to find out what sources/destinations are traversing a NAT gateway, but that won't tell you what the data transfer usage is. I can recommend two options:

The quickest coarse-grained method is to look at the bill. In the AWS console, visit the Billing service and open a bill. Expand the Elastic Compute Cloud section, choose your region, and look at the first line item titled _$0.045 per GB Data Processed by NAT Gateways_. This will show you how much data was processed and the total cost. However, it won't break it down for you by individual NAT Gateway. Best to do this from the AWS Organizations management account to show any savings plan or enterprise discounts.

You can find the data transfer for an individual NAT Gateway through CloudWatch, as mentioned by @smithatlanta. But it's a little trickier to see, for example, the total transfer over a month. Here's how I do it:

1. Open CloudWatch Metrics => All Metrics => _Browse_ tab
2. Search for a NAT gateway by ID. This should bring up a list of 14 metrics.
3. Choose `BytesOutToSource` and `BytesOutToDestination`. If I understand these metrics correctly, the former is ingress data to hosts in your private subnets, and the latter is egress data from your private hosts to the Internet.
4. Switch to the _Graphed metrics_ tab.
5. Choose the time period you're interested in. I like to look at a complete month.
6. Choose _Sum_ for statistic.
7. Choose _Add math_ => _Start with empty expression_
8. Type `m1/m1` and Apply. I will explain this below.
9. Repeat steps 7 & 8 for `m2/m2`. 
10. Start with an empty expression again, and this time use `SUM(m1)/e1`.
11. Repeat step 10 with `SUM(m2)/e2`.
12. Uncheck all the metrics except `e3` and `e4` (the SUM expressions) so that only these two are displayed.
13. For `e3` and `e4`, under the Label column, name these _BytesOutToSource_ and _BytesOutToDestination_ to make their meaning clear.
14. On the _Options_ tab, choose Number as the Widget type.

When you're done it should look something like the image below (the expressions are ordered differently in this image but I think everything else is the same).

![natgw-cloudwatch](https://user-images.githubusercontent.com/503816/209204241-098af2b0-6aa7-4adb-a7bd-a810e5f7a031.png)

Regarding step 8 - why divide a metric by itself? This is best explained in [this StackOverflow answer](https://stackoverflow.com/questions/49712204/cumulative-sum-of-aws-cloudwatch-metric/66681207#66681207). There are some CloudWatch wizards out there.

Eventually I'd like alterNAT to include a CloudWatch dashboard containing this data and similar graphs for the NAT instances.

**Comment by oponomarov-tu** [comment]
Thanks for such a comprehensive answer, @bwhaley! I've also played around Cloudwatch metrics yesterday and was able to reach the same state as on your screenshot with the bellow queries:

```json
{
    "sparkline": false,
    "metrics": [
        [ { "expression": "METRICS()/1000000000000", "label": "Expression2", "id": "e2", "visible": false, "region": "eu-west-1" } ],
        [ "AWS/NATGateway", "BytesOutToDestination", "NatGatewayId", "nat-xxx", { "label": "nat-xxx-TB-egress", "id": "m1", "region": "eu-west-1" } ],
        [ "AWS/NATGateway", "BytesInFromDestination", "NatGatewayId", "nat-xxx", { "label": "nat-xxx-TB-ingress", "id": "m4", "region": "eu-west-1" } ]
    ],
    "view": "singleValue",
    "stat": "Sum",
    "period": 2592000,
    "stacked": false,
    "yAxis": {
        "left": {
            "min": 0
        }
    },
    "region": "eu-west-1",
    "title": "NAT Gateways Data Transfer Monthly"
}
```

**Comment by bwhaley** [comment]
Nice! Looks like a slightly different approach but it gets the job done.
