### ISSUE TITLE
Runtime Python dependencies review

### ISSUE THREAD

**Issue by oponomarov-tu** [1debit/alternat#45]
It looks like only `requests` are required for the Lambda to actually run. Would it make sense to remove `requests` in favour of built-in `urllib3` for the sake of simplicity? It would also make packaging of alternat easier when using Lambda's python runtime instead of containers (addressed in https://github.com/1debit/alternat/pull/44).

**Comment by bwhaley** [comment]
I actually tested `urllib3` first but there were response error. I didn't dig in to it too deeply because I also found that it was easier to set up the unit tests with `requests`. If you have experience unit testing with `urllib3` and you don't see any errors when running connectivity checks then I'd definitely consider it.
