### ISSUE TITLE
Reuse Exiting Nat Gateways 

### ISSUE THREAD

**Issue by abebars** [1debit/alternat#47]
The module takes ownership of the Nat Gateways created in the provided. However, It's possible that each VPC already has provisioned it's own Nat Gateways. Could we supply a list of existing Nat Gateways instead of creating new ones?

**Comment by bwhaley** [comment]
Makes sense to me. Will be addressed in #48.

**Comment by bwhaley** [comment]
https://github.com/1debit/alternat/releases/tag/v0.3.2

**Comment by bwhaley** [comment]
Quick follow up comment here (which I also added to the release): When using create_nat_gateways=false, you must allow alterNAT to manage the `0.0.0.0/0` route. That is, do not use an `aws_route` resource for the NAT Gateway with `0.0.0.0/0` as a destination. alterNAT expects to be able to manage the route on its own using the NAT instance userdata script and the replace-route Lambda function. You can either remove the `aws_route` resource from your configuration or set:
```
  lifecycle {
    ignore_changes = all
  }
```
on the resource to ensure that Terraform ignores it. Otherwise Terraform will attempt to manage the route and will replace it on every run.
